# Generated by Django 3.0.5 on 2020-04-20 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('wait', 'Wait'), ('race', 'Race'), ('over', 'Over')], default='wait', max_length=7)),
                ('current_batch_index', models.PositiveSmallIntegerField(default=0)),
                ('current_entry_index', models.PositiveSmallIntegerField(default=0)),
                ('current_field_index', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Demo')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('points', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=63)),
                ('skill_level', models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediate'), ('adv', 'Advanced')], default='beg', max_length=3)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Demo')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('demo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.Demo')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingAdmin',
            fields=[
                ('admin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Admin')),
                ('points', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=63)),
                ('skill_level', models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediate'), ('adv', 'Advanced')], default='beg', max_length=3)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Team')),
            ],
            options={
                'abstract': False,
            },
            bases=('demo.admin', models.Model),
        ),
    ]
