# Generated by Django 3.0.5 on 2020-04-22 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playingadmin',
            name='admin_ptr',
        ),
        migrations.RemoveField(
            model_name='playingadmin',
            name='team',
        ),
        migrations.AddField(
            model_name='demo',
            name='admin_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='demo',
            name='state',
            field=models.CharField(choices=[('pause', 'Pause'), ('play', 'Play'), ('over', 'Over')], default='wait', max_length=7),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='PlayingAdmin',
        ),
    ]
