# Generated by Django 3.0.5 on 2020-04-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_player_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
