# Generated by Django 3.0.5 on 2020-04-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200418_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='competing',
        ),
    ]
