# Generated by Django 3.0.5 on 2020-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_demo_competing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='state',
            field=models.CharField(choices=[('wait', 'Wait'), ('race', 'Race'), ('over', 'Over')], default='wait', max_length=7),
        ),
    ]
