# Generated by Django 3.0.5 on 2020-04-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200422_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
