# Generated by Django 3.0.5 on 2020-04-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200419_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='current_batch',
            new_name='current_batch_index',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='current_entry',
            new_name='current_entry_index',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='current_field',
            new_name='current_field_index',
        ),
    ]
